### ISSUE TITLE
Story 3: Outside Board invalid Placement Black Piece

### ISSUE THREAD

**Issue by SamGonChec** [SamGonChec/449_The_Gifted_Chimpanzees#31]
AC 3.8 <An illegal black piece placement outside the board>
Given: an ongoing game in the first phase during black piece player turn
When: the black piece player tries to place a black piece outside the board spaces
Then: the black piece is not place 
And: the turn is not changed

**Comment by rpwgc4** [comment]
Unsure how to test this
