### ISSUE TITLE
Story 3: Black Piece second phase placement

### ISSUE THREAD

**Issue by SamGonChec** [SamGonChec/449_The_Gifted_Chimpanzees#32]
AC 3.9 <An illegal black piece placement in second phase>
Given: an ongoing game in the second phase during black piece player turn
When: the black piece player tries to take a white piece
Then: the black piece is not place
And: the turn is not changed

**Comment by rpwgc4** [comment]
I think what you meant is "When the black player tries to place a white piece"?
