### ISSUE TITLE
Story 4: black piece move outside of board

### ISSUE THREAD

**Issue by SamGonChec** [SamGonChec/449_The_Gifted_Chimpanzees#41]
AC 4.8 <An illegal black piece move outside the board space>
Given:  an ongoing game in the second phase during black piece player turn
When: the black piece player makes a move on a space outside the board spaces
Then: the black piece is not moved
And: the turn is not changed

**Comment by rpwgc4** [comment]
Unsure how to test this as written but we do need an issue for making an invalid move in the second phase of the game, i.e. not to an adjacent space
