### ISSUE TITLE
Story 7: Determining if the game is over White less than 3

### ISSUE THREAD

**Issue by SamGonChec** [SamGonChec/449_The_Gifted_Chimpanzees#49]
AC 7.2 <Black piece player can’t make a legal move on their turn>
Given: it’s the Black piece player’s turn during the 3rd phase
When: the player doesn’t have any legal moves to make
Then: the White piece player has won the game.

**Comment by rpwgc4** [comment]
It's impossible for a player to have no moves left when flying is active
